### ISSUE TITLE
Fatal error: Class 'tx_varnish_controller' not found

### ISSUE THREAD

**Issue by julianxhokaxhiu** [snowflakech/typo3-varnish#18] opened 2015-10-01 11:56 UTC
Hi,

On Typo3 6.2.14 where having a strange Fatal error everytime we save a page on the backend. This is the only message that comes out:

```
Fatal error: Class 'tx_varnish_controller' not found in /home/www/p265818/html/typo3/typo3_src/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4434
```

Any idea?

**Comment by andristeiner** [comment] 2015-10-16 14:39
Duplicate of https://github.com/snowflakech/typo3-varnish/issues/16

**Closed by andristeiner** 2015-10-16 14:39 UTC
